# Generated by Django 4.1.1 on 2022-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
