# Generated by Django 4.1.1 on 2022-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.TextField(blank=True, default='default_image_jpg', max_length=500),
        ),
    ]
